#%RAML 1.0

# AMWA-nmos Network Conrtoller API
# (c) ?

title: Network-control-minimal
baseUri: http://example.api.com/x-nmos/netctrl/{version}
version: v1.0
mediaType: application/json
types:
  - NetworkFlow: !include schemas/network-flow-minimal.json
    EmptySchema: !include schemas/empty.json
    ErrorSchema: !include schemas/error.json
    
documentation:
  - title: Overview
    content: |
      The minimal network control API is exposed by NMOS network controller. It provides minimal APIs to
      create and manage network flows, and senders and receivers for the flows. 

/:
  displayName: Base
  get:
    description: List the resources that can be accessed from the base url
    responses:
      200:
        body:
          example: !include ../examples/netctrl-minimal-v1.0-base-get-200.json

/network-flows/{id}:
  displayName: Network flow
  uriParameters:
    id:
      type: string
      pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      description: The globally unique identifier for the network-flow.
      example: cfd02532-1c83-45a5-ae38-1cb7614346db
  get:
    description: Retrieve a single network-flow with the specified guid.
    responses:
      200:
        body: 
          type: !include schemas/netctrl-minimal-v1.0-network-flow-id-get-response.json
          example: !include ../examples/netctrl-minimal-v1.0-network-flow-id-get-200.json
      404:
        description: Returned when the network-flow with guid does not exist.
        body: 
            type: ErrorSchema
  put:
    description: >
      Create a network flow with the specific guid. No subsequent PUT request
      should be made for this flow. Subsequent PUT requests must return error.
    body:
      type: !include schemas/netctrl-minimal-v1.0-network-flow-put-request.json
      example: !include ../examples/netctrl-minimal-v1.0-network-flow-put.json
    responses:
      201:
        description: >
          Returned when the network flow is created successfully.
          No response body.
        body:
          type: EmptySchema
      400:
        description: >
          Returned when the PUT request is incorrectly formatted or has missing values.
        body:
          type: ErrorSchema
  delete:
    description: Delete the network-flow with the specified guid.
    responses:
      204:
        description: >
          Returned when the network-flow is successfully deleted. No response body.
        body:
          type: EmptySchema
      404:
        description: Returned when the network-flow with guid does not exist.
        body:
          type: ErrorSchema

  /senders:
    post:
      description: Add one new sender to this network flow. 
      body:
        type: !include schemas/netctrl-minimal-v1.0-network-flow-sender-post-request.json
        example: !include ../examples/netctrl-minimal-v1.0-network-flow-sender-post.json
      responses:
        200:
          description: >
            Returned when the new sender application is added successfully. No response body.
          body: 
            type: EmptySchema
        400:
          description: >
            Returned when the POST request is incorrectly formatted or missing values.
          body:
            type: ErrorSchema
        404:
          description: >
            Returned when the multicast network-flow with id does not exist.
          body:
            type: ErrorSchema
    /{senderIp}/port/{portAddress}:
      uriParameters:
        senderIp:
          type: string
          description: >
            The sender IP address.
        portAddress:
          type: number
          description: >
            The sender udp port address.
      delete:
        description: >
          Delete sender of this network flow with given ip and port address.
        responses:
          204:
            description: >
              Returned when the sender is successfully deleted.
              No response body.
            body:
              type: EmptySchema
          404:
            description: >
              Returned when no sender with specifid ip and port exists for this flow. 
            body:
              type: ErrorSchema
  /receivers:
    post:
      description: Add receiver to this network flow. 
      body:
        type: !include schemas/netctrl-minimal-v1.0-network-flow-receiver-post-request.json
        example: !include ../examples/netctrl-minimal-v1.0-network-flow-receiver-post.json
      responses:
        200:
          description: >
            Returned when the receiver is successfully added. No response body.
          body: 
            type: EmptySchema
        400:
          description: >
            Returned when the POST request is incorrectly formatted or missing values.
          body:
            type: ErrorSchema
        404:
          description: >
            Returned when the network flow with guid does not exist. 
          body:
            type: ErrorSchema
    /{receiverIp}/port/{portAddress}:
      uriParameters:
        receiverIp:
          type: string
          description: >
            The receiver IP address.
        portAddress:
          type: number
          description: >
            The receiver UDP port address.
      delete:
        description: >
          Delete receiver of this network flow with given ip and port address.
        responses:
          204:
            description: >
              Returned when the receiver is successfully deleted.
              No response body.
            body:
              type: EmptySchema
          404:
            description: >
              Returned when no receiver with specifid ip and port exists for this flow.
            body:
              type: ErrorSchema
